---
title: "lab2markdown"
output: 
  html_document:
    toc: true
    theme: united
date: "2022-09-01"

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Task 1

```{r}
getwd()
```

## Task 2

```{r}
gas <- read.csv("EPAGAS-1.csv")
head(gas)
```

## Task 3

```{r}
mpg.df = gas
mpg=mpg.df$MPG

#Standardize(transform) into z values
z=(mpg-mean(mpg))/sd(mpg)

# Find the z values greater than 3 in size
z[abs(z)>3]

# Find the mpg values corresponding to these z values
mpg[abs(z)>3]

#Find the values of mpg which are possible outliers
mpg[abs(z)>=2 & abs(z)<=3]

mycol = ifelse(abs(z)>3, "Red",
        ifelse(abs(z)>=2 &abs(z)<=3,"Blue", "Black"))  
library(lattice)
dotplot(mpg,col=mycol)
```

## Task 4

```{r}
library(ggplot2)
ggplot(aes(x = MPG), data = gas) + geom_boxplot(fill = "black", notch = TRUE) + ggtitle("Sam Billerbeck")

mn = mean(gas$MPG)
#Q2.
std =  sd(gas$MPG)

"The Chebyshev theorem predicts that 75% of measurements will fall within two standard deviations of the mean."

"Portion of values that fall outside two standard deviations is .04. This corresponds to 96% falling within two standard deviations. This is well within the prediction of the Chebyshev theorem"
length(mpg[abs(z)>2]) / length(mpg)

"The empirical rule states that 95% of values should fall within two standard deviations. As 96% fall within, the empirical rule is valid for this sample set."
```

