---
title: "Lab 1"
output: html_document
date: "2022-08-24"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(ggplot2)
```

# Tasks

## Task 1

```{r}
getwd()
```

## Task 2

```{r}
ddt <- read.csv("DDT.csv")
head(ddt)

```

## Task 3

```{r}
names(ddt)
tab <- table(ddt$SPECIES)
tab
tab2 <- with(ddt, ddt[WEIGHT>800 & SPECIES=="LMBASS",])
tab2
tab3 <-  with(ddt, ddt[DDT>4.0 & RIVER=="SCM",])
tab3
```

## Clicker Questions

```{r}
#Q1.
 mean(ddt$LENGTH)
#Q2.
 sd(ddt$WEIGHT)
#Q3.
 0
#Q4.
 v <- 1:20
 last(v)
```



## Task 4

```{r}
with(ddt, table(RIVER)) -> tab

barplot(tab,beside=TRUE,col=1:4)

with(ddt,table(RIVER,SPECIES)) -> tab2

barplot(tab2,beside=TRUE,col=1:4)
```

## Task 5

```{r}
with(ddt, table(SPECIES)) -> tab
invisible(tab)
pie(tab,col=1:3)

with(ddt, table(RIVER)) -> tab2
invisible(tab2)
pie(tab2,col=4:7)
```
## Task 6

```{r}
with(ddt, table(DDT)) -> tab
invisible(tab)
boxplot(tab,  ylab = "DDT")

with(ddt, table(WEIGHT)) -> tab2
invisible(tab2)
boxplot(tab2,  ylab = "Weight")

with(ddt, table(LENGTH)) -> tab3
invisible(tab3)
boxplot(tab3,  ylab = "Length")
```

## Task 7

```{r}
fishcol=with(ddt,ifelse(SPECIES=="CCATFISH","Red",
                        ifelse(SPECIES=="SMBUFFALO","Blue","Green")))
coplot(WEIGHT~LENGTH|RIVER,data=ddt,col=fishcol)

coplot(DDT~WEIGHT|SPECIES,data=ddt,col=fishcol)
```
## Task 8
```{r}
ggplot(aes(x = SPECIES, y = WEIGHT, fill = RIVER), data = ddt) + geom_boxplot() + ggtitle("Sam Billerbeck")
ggplot(aes(x = RIVER, y = LENGTH, fill = SPECIES), data = ddt) + geom_violin() + ggtitle("Sam Billerbeck")
ggplot(aes(x = WEIGHT, y = LENGTH, fill = SPECIES, colour = SPECIES), data = ddt) + geom_point() + ggtitle("Sam Billerbeck")
```